spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          isolation: 2  # READ_COMMITTED (1=RU, 2=RC, 4=RR, 8=SR)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: hhplus-server
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: "*"

logging:
  level:
    org.hibernate.SQL: DEBUG

# 외부 API 설정
external:
  api:
    url: http://localhost:9090  # 외부 데이터 플랫폼 URL

